# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/fumeron/Documents/Internship_Panama/headset-PiCamera

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/fumeron/Documents/Internship_Panama/headset-PiCamera

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fumeron/Documents/Internship_Panama/headset-PiCamera/CMakeFiles /home/fumeron/Documents/Internship_Panama/headset-PiCamera/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/fumeron/Documents/Internship_Panama/headset-PiCamera/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named RASPBERRY

# Build rule for target.
RASPBERRY: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 RASPBERRY
.PHONY : RASPBERRY

# fast build rule for target.
RASPBERRY/fast:
	$(MAKE) -f CMakeFiles/RASPBERRY.dir/build.make CMakeFiles/RASPBERRY.dir/build
.PHONY : RASPBERRY/fast

#=============================================================================
# Target rules for targets named TestVideoGrab

# Build rule for target.
TestVideoGrab: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 TestVideoGrab
.PHONY : TestVideoGrab

# fast build rule for target.
TestVideoGrab/fast:
	$(MAKE) -f CMakeFiles/TestVideoGrab.dir/build.make CMakeFiles/TestVideoGrab.dir/build
.PHONY : TestVideoGrab/fast

raspberry/TestVideoGrab.o: raspberry/TestVideoGrab.cpp.o
.PHONY : raspberry/TestVideoGrab.o

# target to build an object file
raspberry/TestVideoGrab.cpp.o:
	$(MAKE) -f CMakeFiles/TestVideoGrab.dir/build.make CMakeFiles/TestVideoGrab.dir/raspberry/TestVideoGrab.cpp.o
.PHONY : raspberry/TestVideoGrab.cpp.o

raspberry/TestVideoGrab.i: raspberry/TestVideoGrab.cpp.i
.PHONY : raspberry/TestVideoGrab.i

# target to preprocess a source file
raspberry/TestVideoGrab.cpp.i:
	$(MAKE) -f CMakeFiles/TestVideoGrab.dir/build.make CMakeFiles/TestVideoGrab.dir/raspberry/TestVideoGrab.cpp.i
.PHONY : raspberry/TestVideoGrab.cpp.i

raspberry/TestVideoGrab.s: raspberry/TestVideoGrab.cpp.s
.PHONY : raspberry/TestVideoGrab.s

# target to generate assembly for a file
raspberry/TestVideoGrab.cpp.s:
	$(MAKE) -f CMakeFiles/TestVideoGrab.dir/build.make CMakeFiles/TestVideoGrab.dir/raspberry/TestVideoGrab.cpp.s
.PHONY : raspberry/TestVideoGrab.cpp.s

raspberry/src/VideoGrab.o: raspberry/src/VideoGrab.cpp.o
.PHONY : raspberry/src/VideoGrab.o

# target to build an object file
raspberry/src/VideoGrab.cpp.o:
	$(MAKE) -f CMakeFiles/RASPBERRY.dir/build.make CMakeFiles/RASPBERRY.dir/raspberry/src/VideoGrab.cpp.o
.PHONY : raspberry/src/VideoGrab.cpp.o

raspberry/src/VideoGrab.i: raspberry/src/VideoGrab.cpp.i
.PHONY : raspberry/src/VideoGrab.i

# target to preprocess a source file
raspberry/src/VideoGrab.cpp.i:
	$(MAKE) -f CMakeFiles/RASPBERRY.dir/build.make CMakeFiles/RASPBERRY.dir/raspberry/src/VideoGrab.cpp.i
.PHONY : raspberry/src/VideoGrab.cpp.i

raspberry/src/VideoGrab.s: raspberry/src/VideoGrab.cpp.s
.PHONY : raspberry/src/VideoGrab.s

# target to generate assembly for a file
raspberry/src/VideoGrab.cpp.s:
	$(MAKE) -f CMakeFiles/RASPBERRY.dir/build.make CMakeFiles/RASPBERRY.dir/raspberry/src/VideoGrab.cpp.s
.PHONY : raspberry/src/VideoGrab.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... RASPBERRY"
	@echo "... TestVideoGrab"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... raspberry/TestVideoGrab.o"
	@echo "... raspberry/TestVideoGrab.i"
	@echo "... raspberry/TestVideoGrab.s"
	@echo "... raspberry/src/VideoGrab.o"
	@echo "... raspberry/src/VideoGrab.i"
	@echo "... raspberry/src/VideoGrab.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

